# Generated by Django 3.2 on 2021-05-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IshodBeremennosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Исход беременности',
                'verbose_name_plural': 'Исход беременности',
            },
        ),
        migrations.CreateModel(
            name='KesarevoSechenie1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кесарево сечение (Исход1)',
                'verbose_name_plural': 'Кесарево сечение (Исход1)',
            },
        ),
        migrations.CreateModel(
            name='KesarevoSechenie2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кесарево сечение (Исход2)',
                'verbose_name_plural': 'Кесарево сечение (Исход2)',
            },
        ),
        migrations.CreateModel(
            name='KesarevoSechenie3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кесарево сечение (Исход3)',
                'verbose_name_plural': 'Кесарево сечение (Исход3)',
            },
        ),
        migrations.AlterModelOptions(
            name='ako',
            options={'verbose_name': 'АКО', 'verbose_name_plural': 'АКО'},
        ),
        migrations.AlterModelOptions(
            name='anketa',
            options={'verbose_name': 'Анкета беременной', 'verbose_name_plural': 'Анкета беременной'},
        ),
        migrations.AlterModelOptions(
            name='beremennaya',
            options={'verbose_name': 'Беременная', 'verbose_name_plural': 'Беременные'},
        ),
        migrations.AlterModelOptions(
            name='besplodie',
            options={'verbose_name': 'Бесплодие', 'verbose_name_plural': 'Бесплодие'},
        ),
        migrations.AlterModelOptions(
            name='celnapravleniya',
            options={'verbose_name': 'Цель направления', 'verbose_name_plural': 'Цели направления'},
        ),
        migrations.AlterModelOptions(
            name='fetoplacentarnayanedostatochnost',
            options={'verbose_name': 'фетоплацентарная недостаточность', 'verbose_name_plural': 'фетоплацентарная недостаточность'},
        ),
        migrations.AlterModelOptions(
            name='formasujeniyataza',
            options={'verbose_name': 'Форма сужения таза', 'verbose_name_plural': 'Форма сужения таза'},
        ),
        migrations.AlterModelOptions(
            name='geneticheskiefaktori',
            options={'verbose_name': 'Генетический фактор', 'verbose_name_plural': 'Генетические факторы'},
        ),
        migrations.AlterModelOptions(
            name='gestacionniysaharniydiabed',
            options={'verbose_name': 'Гестационный сахарный диабет', 'verbose_name_plural': 'Гестационный сахарный диабет'},
        ),
        migrations.AlterModelOptions(
            name='gibelploda',
            options={'verbose_name': 'Гибель плода', 'verbose_name_plural': 'Гибель плода'},
        ),
        migrations.AlterModelOptions(
            name='ishod',
            options={'verbose_name': 'Исход', 'verbose_name_plural': 'Исход'},
        ),
        migrations.AlterModelOptions(
            name='iskustvenniyabort',
            options={'verbose_name': 'Искусственный аборт', 'verbose_name_plural': 'Искусственный аборт'},
        ),
        migrations.AlterModelOptions(
            name='kesarevosechenie',
            options={'verbose_name': 'Кесарево сечение для анкеты беременной', 'verbose_name_plural': 'Кесарево сечение для анкеты беременной'},
        ),
        migrations.AlterModelOptions(
            name='koagulopatiya',
            options={'verbose_name': 'Коагулопатия', 'verbose_name_plural': 'Коагулопатия'},
        ),
        migrations.AlterModelOptions(
            name='menstrualnayafunkciya',
            options={'verbose_name': 'Менструальная функция', 'verbose_name_plural': 'Менструальная функции'},
        ),
        migrations.AlterModelOptions(
            name='mestoishoda',
            options={'verbose_name': 'Место исхода', 'verbose_name_plural': 'Место исхода'},
        ),
        migrations.AlterModelOptions(
            name='mkb10',
            options={'verbose_name': 'Код по МКБ10', 'verbose_name_plural': 'Коды по МКБ10'},
        ),
        migrations.AlterModelOptions(
            name='mnogoplodie',
            options={'verbose_name': 'Многоплодие', 'verbose_name_plural': 'Многоплодие'},
        ),
        migrations.AlterModelOptions(
            name='nalichievprporezultatamuzi',
            options={'verbose_name': 'Наличие ВПР по результатам УЗИ', 'verbose_name_plural': 'Наличие ВПР по результатам УЗИ'},
        ),
        migrations.AlterModelOptions(
            name='nastuplenieberemennostivrezultate',
            options={'verbose_name': 'Наступление беременности в результате ЭКО', 'verbose_name_plural': 'Наступление беременности в результате ЭКО'},
        ),
        migrations.AlterModelOptions(
            name='nepravilnoepolojenieploda',
            options={'verbose_name': 'Неправильное положение плода', 'verbose_name_plural': 'Неправильное положение плода'},
        ),
        migrations.AlterModelOptions(
            name='novorojdenniy',
            options={'verbose_name': 'Новорожденный', 'verbose_name_plural': 'Новорожденныe'},
        ),
        migrations.AlterModelOptions(
            name='obsheesostoyanieploda',
            options={'verbose_name': 'Общее состояние плода', 'verbose_name_plural': 'Общее состояние плода'},
        ),
        migrations.AlterModelOptions(
            name='oslojneniyaberemennostianamez',
            options={'verbose_name': 'Осложнения беременности (анамез)', 'verbose_name_plural': 'Осложнения беременности (анамез)'},
        ),
        migrations.AlterModelOptions(
            name='oslojneniyaiskustvenniyabort',
            options={'verbose_name': 'Осложнения', 'verbose_name_plural': 'Осложнения'},
        ),
        migrations.AlterModelOptions(
            name='oslojneniyarodov',
            options={'verbose_name': 'Осложнения родов', 'verbose_name_plural': 'Осложнения родов'},
        ),
        migrations.AlterModelOptions(
            name='paritetberemennosti',
            options={'verbose_name': 'Паритет беременности', 'verbose_name_plural': 'Паритет беременности'},
        ),
        migrations.AlterModelOptions(
            name='predlejanieplacenti',
            options={'verbose_name': 'Предлежание плаценты', 'verbose_name_plural': 'Предлежание плаценты'},
        ),
        migrations.AlterModelOptions(
            name='preeklampsiya',
            options={'verbose_name': 'Преэклампсия', 'verbose_name_plural': 'Преэклампсия'},
        ),
        migrations.AlterModelOptions(
            name='rezussensibilizaciya',
            options={'verbose_name': 'Резус сенсибилизация', 'verbose_name_plural': 'Резус сенсибилизация'},
        ),
        migrations.AlterModelOptions(
            name='saharniydiabed',
            options={'verbose_name': 'Сахарный диабет', 'verbose_name_plural': 'Сахарный диабет'},
        ),
        migrations.AlterModelOptions(
            name='samoproizvolniyabort',
            options={'verbose_name': 'Самопроизвольный аборт', 'verbose_name_plural': 'Самопроизвольный аборт'},
        ),
        migrations.AlterModelOptions(
            name='semeynoepolojenie',
            options={'verbose_name': 'Семейное положение', 'verbose_name_plural': 'Семейное положение'},
        ),
        migrations.AlterModelOptions(
            name='smena_jk_u_beremennoy',
            options={'verbose_name_plural': 'Смена ЖК у беременной'},
        ),
        migrations.AlterModelOptions(
            name='smertnovorojdennogo',
            options={'verbose_name': 'Смерть новорожденного', 'verbose_name_plural': 'Смерть новорожденного'},
        ),
        migrations.AlterModelOptions(
            name='stepenriska',
            options={'verbose_name': 'Степень риска', 'verbose_name_plural': 'Степени риска'},
        ),
        migrations.AlterModelOptions(
            name='stepenriskaposleishoda',
            options={'verbose_name': 'Степень риска после исхода', 'verbose_name_plural': 'Степень риска после исхода'},
        ),
        migrations.AlterModelOptions(
            name='stepensujeniyataza',
            options={'verbose_name': 'Степень сужения таза', 'verbose_name_plural': 'Степень сужения таза'},
        ),
        migrations.AlterModelOptions(
            name='tipbesplodiya',
            options={'verbose_name': 'Тип бесплодия', 'verbose_name_plural': 'Типы бесплодия'},
        ),
        migrations.AlterModelOptions(
            name='tiporganizacii',
            options={'verbose_name': 'Тип организации', 'verbose_name_plural': 'Тип организации'},
        ),
        migrations.AlterModelOptions(
            name='urovenbetahgch',
            options={'verbose_name': 'Уровень бета ХГЧ', 'verbose_name_plural': 'Уровень бета ХГЧ'},
        ),
        migrations.AlterModelOptions(
            name='urovenmedobsluzivaniya',
            options={'verbose_name': 'Уровень медецинского обслуживания', 'verbose_name_plural': 'Уровень медецинского обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='urovenpappa',
            options={'verbose_name': 'Уровень РРАР-А', 'verbose_name_plural': 'Уровень РРАР-А'},
        ),
        migrations.AlterModelOptions(
            name='vzyatapodnabludenie',
            options={'verbose_name': 'Взята под наблюдение', 'verbose_name_plural': 'Взята под наблюдение'},
        ),
        migrations.AlterModelOptions(
            name='zabolevanieshitovidnoy',
            options={'verbose_name': 'Заболевание щитовидной железы', 'verbose_name_plural': 'Заболевания щитовидной железы'},
        ),
        migrations.AddField(
            model_name='ishod',
            name='prichina_smerti_materi_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='rezus_faktori_beremennoy_otca',
            field=models.IntegerField(blank=True, choices=[(1, '+/+'), (2, '+/-'), (3, '-/+'), (4, '-/-')], null=True, verbose_name='Резус факторы беременной/отца'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='somaticheskie_pokazateli_girsutizm',
            field=models.BooleanField(default=False, verbose_name='Гирсутизм'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='somaticheskie_pokazateli_muzskoy',
            field=models.BooleanField(default=False, verbose_name='Мужской тип телосложения'),
        ),
        migrations.AddField(
            model_name='ishod',
            name='ishod_beremennosti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ishodberemennosti', verbose_name='Исход беременности'),
        ),
        migrations.AddField(
            model_name='ishod',
            name='kesarevo_sechenie1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kesarevosechenie1', verbose_name='Кесарево сечение'),
        ),
        migrations.AddField(
            model_name='ishod',
            name='kesarevo_sechenie2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kesarevosechenie2', verbose_name='Кесарево сечение'),
        ),
        migrations.AddField(
            model_name='ishod',
            name='kesarevo_sechenie3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kesarevosechenie3', verbose_name='Кесарево сечение'),
        ),
    ]
