# Generated by Django 3.2 on 2021-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210505_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='data_provedeniya_prenatalnogo_konsiliuma',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения пренатального консилиума'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='data_zapolneniya_anketi_vrachem',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заполнения анкеты врачем'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='data_pervogo_dnya_posledney_menstruacii',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первого дня последней менструации'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='data_rojdeniya',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='data_vzyatiya',
            field=models.DateField(blank=True, null=True, verbose_name='Дата взятия'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='data_ishoda',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исхода'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='data_smerti_materi',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти матери'),
        ),
    ]
