# Generated by Django 3.2 on 2021-05-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210505_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='novorojdenniy',
            name='nomer_novorojdennogo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер новорожденного'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='ocenka_po_shkale_apgar_na1_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка по шкале Апгар на 1 мин, баллы'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='ocenka_po_shkale_apgar_na5_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка по шкале Апгар на 5 мин, баллы'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='pol_novorojdennogo',
            field=models.IntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж'), (3, 'Неизвестен'), (4, 'Интерсекс')], null=True),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='rost_novorojdennogo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рост новорожденного'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='smert_novorojdennogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.smertnovorojdennogo', verbose_name='Смерть новорожденного'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='ves_novorojdennogo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес новорожденного'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='vpr_novorojdennogo_po_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mkb10', verbose_name='ВПР новорожденного (код по МКБ-10)'),
        ),
    ]
