# Generated by Django 3.2.2 on 2021-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210505_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beremennaya',
            name='nomer',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер'),
        ),
    ]
