# Generated by Django 3.2.2 on 2021-05-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_beremennaya_nomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='napravlenie',
            name='cel_napravleniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.celnapravleniya', verbose_name='Цель направления'),
        ),
        migrations.AddField(
            model_name='novorojdenniy',
            name='nomer_beremennoy',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beremennaya', verbose_name='Беременная'),
        ),
    ]
