# Generated by Django 3.2.2 on 2021-05-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210508_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='beremennaya',
            name='jk_beremennoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medorganizacia', verbose_name='ЖК ведущая организацию'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='nomer',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер карты'),
        ),
    ]
