# Generated by Django 3.2.2 on 2021-05-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210510_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smena_jk_u_beremennoy',
            name='nomer_beremennoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beremennaya', verbose_name='Номер карты беременной'),
        ),
    ]
