# Generated by Django 3.2.2 on 2021-05-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210515_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polzovateli',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roli', verbose_name='Роль'),
        ),
    ]
