# Generated by Django 3.2.2 on 2021-05-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_polzovateli_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='diagnoz_oslojneniya_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smerti_novorojdennogo1', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AddField(
            model_name='anketa',
            name='diagnoz_soputstvuyshiy_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smerti_novorojdennogo2', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
    ]
