# Generated by Django 3.2.2 on 2021-05-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210522_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='diagnoz_oslojneniya_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoz_oslojneniya_mkb10', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='diagnoz_soputstvuyshiy_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoz_soputstvuyshiy_mkb10', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
    ]
