# Generated by Django 3.2.2 on 2021-05-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_beremennaya_rubec_na_matke'),
    ]

    operations = [
        migrations.AddField(
            model_name='beremennaya',
            name='infekcionnie_bolezni_toksoplazmoz',
            field=models.BooleanField(default=False, verbose_name='Токсоплазмоз'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='infekcionnie_bolezni_virusniy_cmvi',
            field=models.BooleanField(default=False, verbose_name='ЦМВИ'),
        ),
    ]
