# Generated by Django 3.2.2 on 2021-05-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
