# Generated by Django 3.2.2 on 2021-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_nervnoy_chmt',
            field=models.BooleanField(default=False, verbose_name='ЧМТ'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_nervnoy_narushenie',
            field=models.BooleanField(default=False, verbose_name='Нарушение мозгового кровообращения в прошлом или настоящем'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_dihaniya_astma',
            field=models.BooleanField(default=False, verbose_name='Бронхиальная астма'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_dihaniya_bronh',
            field=models.BooleanField(default=False, verbose_name='Бронхоэктатическая болезнь'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_dihaniya_lobektomiya',
            field=models.BooleanField(default=False, verbose_name='Лобэктомия, пульмонэктомия'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_dihaniya_pnevmoniya',
            field=models.BooleanField(default=False, verbose_name='Пневмония'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_mochv_gidronefroz',
            field=models.BooleanField(default=False, verbose_name='Гидронефроз'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_mochv_glomer',
            field=models.BooleanField(default=False, verbose_name='Гломерулонефрит'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_mochv_hpn',
            field=models.BooleanField(default=False, verbose_name='Пиелонефрит ХПН 1-3'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_mochv_pochka',
            field=models.BooleanField(default=False, verbose_name='Единственная почка'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_mochv_polikistoz',
            field=models.BooleanField(default=False, verbose_name='Поликистоз почек'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_organov_mochv_tuberkulez',
            field=models.BooleanField(default=False, verbose_name='Туберкулез почек'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_gipertoniya',
            field=models.BooleanField(default=False, verbose_name='Гипертоническая болезнь'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_miokarda',
            field=models.BooleanField(default=False, verbose_name='Болезнь миокарда, эндокарда и перикарда'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_narush',
            field=models.BooleanField(default=False, verbose_name='Нарушение ритмов сердца'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_operirovannoe',
            field=models.BooleanField(default=False, verbose_name='Оперированное сердце'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_poroki_serdca_bez',
            field=models.BooleanField(default=False, verbose_name='Пороки сердца без недост-ти кровообращения'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_poroki_serdca_c',
            field=models.BooleanField(default=False, verbose_name='Пороки сердца с недост-ти кровообращения'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bolezni_sistemi_krovoob_sosudov',
            field=models.BooleanField(default=False, verbose_name='Болезни сосудов'),
        ),
    ]
