# Generated by Django 3.2.2 on 2021-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vesadliaozenkistepeniriska'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesadliaozenkistepeniriska',
            options={'verbose_name': 'Веса для оценки', 'verbose_name_plural': '-Веса для оценки степени риска-'},
        ),
        migrations.RemoveField(
            model_name='vesadliaozenkistepeniriska',
            name='znachenie',
        ),
        migrations.AddField(
            model_name='vesadliaozenkistepeniriska',
            name='znachenie_boolean',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Истина/Да'), (False, 'Ложь/Нет')], default=1, help_text='Параметр с высшим приоритетом. Выбрав значение остальные будут игнорироваться', verbose_name='01. Значение при оценки Истина/Ложь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vesadliaozenkistepeniriska',
            name='znachenie_chislo',
            field=models.CharField(blank=True, help_text='Параметр со вторым приоритетом. Будет доступен если параметр с первым приоритетом не выбран', max_length=255, null=True, verbose_name='02. Значение при оценки число/строка'),
        ),
        migrations.AddField(
            model_name='vesadliaozenkistepeniriska',
            name='znachenie_do',
            field=models.IntegerField(default=0, verbose_name='03. Значение при оценки до'),
        ),
        migrations.AddField(
            model_name='vesadliaozenkistepeniriska',
            name='znachenie_ot',
            field=models.IntegerField(default=0, verbose_name='03. Значение при оценки от'),
        ),
        migrations.AlterField(
            model_name='vesadliaozenkistepeniriska',
            name='model_gde_smotret',
            field=models.CharField(blank=True, choices=[('Anketi', 'Анкеты'), ('Beremennaya', 'Беременная')], max_length=255, null=True, verbose_name='Модель где смотреть'),
        ),
    ]
