# Generated by Django 3.2.2 on 2021-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210604_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesadliaozenkistepeniriska',
            name='znachenie_boolean',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Истина/Да'), (False, 'Ложь/Нет')], help_text='Параметр с высшим приоритетом. Выбрав значение остальные будут игнорироваться', null=True, verbose_name='01. Значение при оценки Истина/Ложь'),
        ),
    ]
