# Generated by Django 3.2.2 on 2021-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vesadliaozenkistepeniriska_znachenie_boolean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepenriska',
            options={'verbose_name': 'Степень риска', 'verbose_name_plural': '-Степени риска-'},
        ),
        migrations.AddField(
            model_name='stepenriska',
            name='summa_vesov_do',
            field=models.IntegerField(default=0, verbose_name='Сумма весов оценки до(включительно)'),
        ),
        migrations.AddField(
            model_name='stepenriska',
            name='summa_vesov_ot',
            field=models.IntegerField(default=0, verbose_name='Сумма весов оценки от(включительно)'),
        ),
        migrations.AlterField(
            model_name='stepenriska',
            name='nazvanie',
            field=models.CharField(choices=[('низкая', 'низкая'), ('средняя', 'средняя'), ('высокая', 'высокая')], default=1, max_length=255, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
