# Generated by Django 3.2.2 on 2021-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_konsultaciaya_kontakt_s_socialno_tuberkulez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultaciaya',
            name='kontakt_s_socialno_tuberkulez',
            field=models.IntegerField(blank=True, null=True, verbose_name='Туберкулез'),
        ),
    ]
