# Generated by Django 3.2.2 on 2021-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210613_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napravlenie',
            name='diagnoz_podtverjden',
            field=models.IntegerField(blank=True, choices=[(None, 'Неизвестно'), (0, 'Нет'), (1, 'Да')], default=False, null=True, verbose_name='Диагноз подтвержден?'),
        ),
    ]
