# Generated by Django 3.2.2 on 2021-06-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_napravlenie_diagnoz_podtverjden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishod',
            name='nomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beremennaya', verbose_name='Номер карты беременной'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='nomer_anketi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beremennaya', verbose_name='Номер карты беременной'),
        ),
    ]
