# Generated by Django 3.2.2 on 2021-07-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210616_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beremennaya',
            name='nomer',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер карты'),
            preserve_default=False,
        ),
    ]
