# Generated by Django 3.2.2 on 2021-07-29 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_alter_beremennaya_nomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='diagnoz_oslojneniya_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoz_oslojneniya_mkb10', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='diagnoz_osnovnoy_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mkb10', verbose_name='Диагноз основной (код по МКБ-10)'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='diagnoz_soputstvuyshiy_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoz_soputstvuyshiy_mkb10', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='familiya_vracha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.doctor', verbose_name='Фамилия врача заполнившего анкету'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='fetoplacentarnaya_nedostatochnost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fetoplacentarnayanedostatochnost', verbose_name='Фетоплацентарная недостаточность'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='mnogoplodie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mnogoplodie', verbose_name='Многоплодие'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='nalichie_vpr_po_rezultatam_uzi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.nalichievprporezultatamuzi', verbose_name='Наличие ВПР по результатам УЗИ'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='nepravilnoe_polojenie_ploda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.nepravilnoepolojenieploda', verbose_name='Неправильное положение плода'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='nomer_anketi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.beremennaya', verbose_name='Номер карты беременной'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='obshee_sostoyanie_ploda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.obsheesostoyanieploda', verbose_name='Общее состояние плода'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='predlejanie_placenti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.predlejanieplacenti', verbose_name='Предлежание плаценты'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='preeklampsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.preeklampsiya', verbose_name='Преэклампсия'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='rezus_sensibilizaciya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rezussensibilizaciya', verbose_name='Резус-сенсибилизация'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='uroven_beta_hgch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.urovenbetahgch', verbose_name='Уровень бета ХГЧ'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='uroven_papp_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.urovenpappa', verbose_name='Уровень РАРР-А'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='ako',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ako', verbose_name='АКО'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='besplodie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.besplodie', verbose_name='Бесплодие'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='forma_sujeniya_taza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.formasujeniyataza', verbose_name='Форма сужения таза'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='geneticheskie_faktori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.geneticheskiefaktori', verbose_name='Генетические факторы'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='gestacionniy_saharniy_diabed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gestacionniysaharniydiabed', verbose_name='Гестационный cахарный диабед'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='iskustvenniy_abort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.iskustvenniyabort', verbose_name='Искусственный аборт'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='iskustvenniy_abort_oslojneniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.oslojneniyaiskustvenniyabort', verbose_name='Осложнения'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='jk_beremennoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia', verbose_name='ЖК ведущая организацию'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='kesarevo_sechenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kesarevosechenie', verbose_name='Кесарево сечение'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='koagulopatiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.koagulopatiya', verbose_name='Коагулопатия'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='menstrualnaya_funkciya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.menstrualnayafunkciya', verbose_name='Менструальная функция'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='mesto_postoyannogo_projivaniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rayon', verbose_name='Место постоянного проживания'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='nastuplenie_beremennosti_v_rezultate_eco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.nastuplenieberemennostivrezultate', verbose_name='Наступление беременности в результате ЭКО'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='oslojneniya_beremennosti_anemez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.oslojneniyaberemennostianamez', verbose_name='Осложнение беременности (анамез)'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='oslojneniya_rodov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.oslojneniyarodov', verbose_name='Осложнения родов'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='paritet_beremennosti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.paritetberemennosti', verbose_name='Паритет беременности'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='saharniy_diabed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.saharniydiabed', verbose_name='Сахарный диабед'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='samoproizvolniy_abort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.samoproizvolniyabort', verbose_name='Самопроизвольный аборт'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='semeynoe_polojenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.semeynoepolojenie', verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='stepen_riska',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stepenriska', verbose_name='Степень риска'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='stepen_sujeniya_taza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stepensujeniyataza', verbose_name='Степень сужения таза'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='tip_besplodiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipbesplodiya', verbose_name='Тип бесплодия'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='vrach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='vzyata_pod_nabludenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vzyatapodnabludenie', verbose_name='Взята под наблюдение'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='zabolevanie_shitovidnoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.zabolevanieshitovidnoy', verbose_name='Заболевание щитовидной железы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='med_organiizaciya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia', verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='gibel_ploda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gibelploda', verbose_name='Гибель плода'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='ishod_beremennosti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ishodberemennosti', verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='kesarevo_sechenie1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kesarevosechenie1', verbose_name='Кесарево сечение'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='kesarevo_sechenie2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kesarevosechenie2', verbose_name='Кесарево сечение'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='kesarevo_sechenie3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kesarevosechenie3', verbose_name='Кесарево сечение'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='mesto_ishoda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mestoishoda', verbose_name='Место исхода'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='nomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.beremennaya', verbose_name='Номер карты беременной'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='prichina_smerti_materi_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='ishod',
            name='stepen_riska_posle_ishoda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stepenriskaposleishoda', verbose_name='Степень риска после исхода'),
        ),
        migrations.AlterField(
            model_name='konsultaciaya',
            name='nomer_beremennoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.beremennaya', verbose_name='Номер беременной'),
        ),
        migrations.AlterField(
            model_name='konsultaciaya',
            name='otpravitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.polzovateli', verbose_name='Отправитель (роль)'),
        ),
        migrations.AlterField(
            model_name='medorganizacia',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rayon', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='medorganizacia',
            name='tip_organizacii',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.PROTECT, to='core.tiporganizacii', verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='medorganizacia',
            name='uroven_med_obclujivaniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.urovenmedobsluzivaniya', verbose_name='Уровень медецинского обслуживания'),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='cel_napravleniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.celnapravleniya', verbose_name='Цель направления'),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='nomer_beremennoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.beremennaya', verbose_name='Номер беременной'),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='punkt_napravleniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia', verbose_name='Пункт направления'),
        ),
        migrations.AlterField(
            model_name='novorojdenniy',
            name='nomer_beremennoy',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.beremennaya', verbose_name='Беременная'),
        ),
        migrations.AlterField(
            model_name='novorojdenniy',
            name='prichina_smerti_materi_po_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smerti_novorojdennogo', to='core.mkb10', verbose_name='Причина смерти матери по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='novorojdenniy',
            name='smert_novorojdennogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.smertnovorojdennogo', verbose_name='Смерть новорожденного'),
        ),
        migrations.AlterField(
            model_name='novorojdenniy',
            name='vpr_novorojdennogo_po_mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mkb10', verbose_name='ВПР новорожденного (код по МКБ-10)'),
        ),
        migrations.AlterField(
            model_name='polzovateli',
            name='med_organiizaciya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia', verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='polzovateli',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.roli', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='polzovateli',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='smena_jk_u_beremennoy',
            name='nomer_beremennoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.beremennaya', verbose_name='Номер карты беременной'),
        ),
        migrations.AlterField(
            model_name='smena_jk_u_beremennoy',
            name='novaya_JK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia', verbose_name='Новая ЖК'),
        ),
    ]
