# Generated by Django 3.2.2 on 2021-07-29 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_sotrudniki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotrudnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(1, 'админ края'), (2, 'админ ЖК'), (3, 'врач ЖК'), (4, 'консультант ЖК')], verbose_name='Роль')),
                ('med_organizacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sotrudnic', to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
        ),
        migrations.DeleteModel(
            name='Sotrudniki',
        ),
    ]
