# Generated by Django 3.2.2 on 2021-07-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210729_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sotrudnik',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': '-Сотрудники-'},
        ),
        migrations.AlterField(
            model_name='sotrudnik',
            name='med_organizacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medorganizacia', verbose_name='Мед организация'),
        ),
    ]
