# Generated by Django 3.2.2 on 2021-07-29 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_auto_20210729_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polzovateli',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': '-Сотрудники-'},
        ),
        migrations.AlterModelOptions(
            name='roli',
            options={'verbose_name': 'Роль', 'verbose_name_plural': '-Роли-'},
        ),
        migrations.AlterField(
            model_name='polzovateli',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.roli', verbose_name='Роль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polzovateli',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.DeleteModel(
            name='Sotrudnik',
        ),
    ]
