# Generated by Django 3.2.2 on 2021-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210824_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='beremennaya',
            name='bal_riska_po_ankete',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балов риска по анкете'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='bal_riska_po_ishodu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балов риска по исходу'),
        ),
        migrations.AddField(
            model_name='beremennaya',
            name='ishod_tmp',
            field=models.BooleanField(blank=True, null=True, verbose_name='Исход по старым данным'),
        ),
    ]
