# Generated by Django 3.2.2 on 2021-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210824_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='beremennaya',
            name='qf1295_bolezni_nervnoy_chmt',
            field=models.BooleanField(default=False, verbose_name='ЧМТ'),
        ),
        migrations.AlterField(
            model_name='beremennaya',
            name='qf1290_bolezni_nervnoy_narushenie',
            field=models.BooleanField(default=False, verbose_name='Нарушение мозгового кровообращения в прошлом или настоящем'),
        ),
    ]
