# Generated by Django 3.2.2 on 2021-11-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_konsultaciaya_otpravleno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otchety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_otcheta', models.IntegerField(blank=True, null=True, verbose_name='Код')),
                ('nazvanie_otcheta', models.CharField(max_length=255, verbose_name='Наименование')),
                ('tip_otcheta', models.CharField(choices=[('по текущим', 'по текущим'), ('по завершенным', 'по завершенным')], max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Отчеты',
                'verbose_name_plural': '-Отчеты-',
            },
        ),
    ]
