# Generated by Django 3.2.2 on 2021-11-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_otchety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otchety',
            name='kod_otcheta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код'),
        ),
    ]
