# Generated by Django 3.2.2 on 2021-12-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_otchety_kod_otcheta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultaciaya',
            name='otpravitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.polzovateli', verbose_name='Отправитель (роль)'),
        ),
    ]
