# Generated by Django 3.2.2 on 2021-12-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20211222_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultaciaya',
            name='egp',
            field=models.IntegerField(blank=True, choices=[(None, 'Неизвестно'), (0, 'Нет'), (1, 'Да')], default=False, null=True, verbose_name='ЭГП'),
        ),
        migrations.AlterField(
            model_name='konsultaciaya',
            name='oaa',
            field=models.IntegerField(blank=True, choices=[(None, 'Неизвестно'), (0, 'Нет'), (1, 'Да')], default=False, null=True, verbose_name='ОАА'),
        ),
        migrations.AlterField(
            model_name='konsultaciaya',
            name='rh_sensibilizaciya',
            field=models.IntegerField(blank=True, choices=[(None, 'Неизвестно'), (0, 'Нет'), (1, 'Да')], default=False, null=True, verbose_name='Rh-сенсибилизация'),
        ),
        migrations.AlterField(
            model_name='konsultaciaya',
            name='rubec_na_matke',
            field=models.IntegerField(blank=True, choices=[(None, 'Неизвестно'), (0, 'Нет'), (1, 'Да')], default=False, null=True, verbose_name='Рубец на матке'),
        ),
    ]
